version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies..."
#      - pip install -r requirements.txt -t lib # external libraries are saved to lib folder on root dir
  pre_build:
    commands:
      - sam validate --template ${CODEBUILD_SRC_DIR}/template.yaml
  build:
    commands:
      - echo ${CODEBUILD_SRC_DIR}
#      - sam build --template ${CODEBUILD_SRC_DIR}/template.yaml
  post_build:
    commands:
      - sam package --output-template-file packaged.yaml --s3-bucket codebuild-practice9784

artifacts:
  files:
    - packaged.yaml
