version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - sam validate --template ${CODEBUILD_SRC_DIR}/template.yaml
  build:
    commands:
      - pip install -r function/requirements.txt
#      - sam build --template ${CODEBUILD_SRC_DIR}/template.yaml
      - sam build
  post_build:
    commands:
      - cd .aws-sam/build/
      - sam package --template-file template.yaml --output-template-file packaged.yaml --s3-bucket codebuild-practice9784 --debug
#      - sam package --s3-bucket codebuild-practice9784   this isn't needed assuming we created a codebuild through the console and already designated an s3 bucket to push artifacts to.

artifacts:
  files:
    - packaged.yaml
